name: Build app and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node.js 18.9.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.1
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      # 部署到阿里云
      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./dist"
          REMOTE_HOST: "49.234.156.163"
          REMOTE_USER: "root"
          TARGET: "/root/"