name: Build app and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node.js 18.9.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.1
      - name: npm install
        run:  yarn cache clean && yarn install
      - name: npm build
        run: yarn build
      # 部署到阿里云
      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

          ARGS: "-rlgoDzvc -i"
          SOURCE: ".vuepress/dist/"
          REMOTE_HOST: "110.40.229.45"
          REMOTE_USER: "root"
          TARGET: "/home/www/thebyte.com.cn"
          SCRIPT_BEFORE: |
            whoami
            ls -al